name: MacOS CI

on: [ push, pull_request ]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: brew install git ninja qt molten-vk vulkan-tools

      - name: Configure CMake
        run: >
          cmake -B "${{ github.workspace }}/build"
          -G Ninja
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_OSX_ARCHITECTURES="arm64"
          -S ${{ github.workspace }}

      - name: Build Tests
        run: cmake --build "${{ github.workspace }}/build" --config Release --target unlogic-test

      - name: Run Tests
        working-directory: "${{ github.workspace }}/build"
        run: ./unlogic/unlogic-test --gtest_shuffle

      - name: Build Calculator
        run: cmake --build "${{ github.workspace }}/build" --config Release --target unlogic-calculator