name: Windows CI

on: [ push, pull_request ]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: choco install aqt

      - name: Setup Vulkan SDK
        uses: humbletim/setup-vulkan-sdk@v1.2.0
        with:
          vulkan-query-version: 1.2.198.1

      - name: Install QT and Modules
        run: aqt install-qt --outputdir "${{ github.workspace }}\qt6.8.1" windows desktop 6.8.1 win64_msvc2022_64 -m all

      - name: Configure CMake
        run: >
          cmake -B "${{ github.workspace }}\build"
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_PREFIX_PATH="${{ github.workspace }}\qt6.8.1\6.8.1\lib\cmake"
          -S ${{ github.workspace }}

      - name: Build Tests
        run: cmake --build "${{ github.workspace }}\build" --config Release --target unlogic-test

      - name: Run Tests
        working-directory: "${{ github.workspace }}\build"
        run: .\Release\unlogic\unlogic-test --gtest_shuffle

      - name: Build Calculator
        run: cmake --build "${{ github.workspace }}\build" --config Release --target unlogic-calculator
