name: Unlogic CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: Install System Dependencies
      run: sudo apt install -y build-essential cmake llvm-17-dev wget ninja-build bison flex libgtkmm-4.0-dev
    - name: Configure Project
      run: mkdir cmake-build-release && cd cmake-build-release && cmake -DCMAKE_BUILD_TYPE=Release -G "Ninja" ..
    - name: Build Tests
      run: cd cmake-build-release && cmake --build . --target unlogic-test
    - name: Run Tests
      run: cd cmake-build-release && ./unlogic-test
