name: Unlogic CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Update Package Manager
        run: sudo apt update
      - name: Install System Dependencies
        run: sudo apt install -y build-essential cmake ninja-build llvm-18-dev
      - uses: actions/checkout@v4
      - name: Configure Project
        run: |
          mkdir cmake-build-release
          cd cmake-build-release
          cmake .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DCONFIGURE_CALCULATOR=OFF \
            -G "Ninja"
      - name: Build Unlogic
        run: cd cmake-build-release && cmake --build . --target unlogic
      - name: Build Tests
        run: cd cmake-build-release && cmake --build . --target unlogic-test
      - name: Run Tests
        run: cd cmake-build-release && ./unlogic-test
