# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Unlogic CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: Install System Dependencies
      run: sudo apt install -y python3 pipx build-essential cmake llvm-17-dev
    - name: Install Conan
      run: sudo pipx install conan
    - name: Configure Conan
      run: conan profile detect
    - uses: actions/checkout@v4
    - name: Configure Project and Install Conan Dependencies
      run: sudo ./kickstart.sh Release
    - name: Configure Project
      run: cd cmake-build-release && cmake .. -DCMAKE_TOOLCHAIN_FILE="conan_toolchain.cmake" -DCMAKE_BUILD_TYPE=Release -G "Ninja"
    - name: Build Project
      run: cd cmake-build-release && cmake --build . --target unlogic-test
    - name: Unlogic Tests
      run: cd cmake-build-release && ./unlogic-test
