name: Unlogic CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: Install System Dependencies
      run: sudo apt install -y build-essential cmake llvm-17-dev wget ninja-build bison flex
    - name: Install Conan
      run: wget https://github.com/conan-io/conan/releases/download/2.2.2/conan-2.2.2-amd64.deb && sudo dpkg -i conan-2.2.2-amd64.deb
    - name: Configure Conan
      run: conan profile detect
    - uses: actions/checkout@v4
    - name: Configure Project and Install Conan Dependencies
      run: mkdir cmake-build-release && conan install . --output-folder="cmake-build-release" --build=missing -s build_type="Release" -c tools.system.package_manager:mode=install -c tools.system.package_manager:sudo=True
    - name: Configure Project
      run: cd cmake-build-release && cmake .. --preset conan-release -G "Ninja"
    - name: Build Tests
      run: cd cmake-build-release && cmake --build . --target unlogic-test
    - name: Run Tests
      run: cd cmake-build-release && ./unlogic-test
