name: Unlogic CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: Update Package Manager
      run: sudo apt update && sudo apt upgrade
    - name: Install System Dependencies
      run: sudo apt install -y build-essential cmake ninja-build llvm-19-dev qt6-base-dev
    - uses: actions/checkout@v4
    - name: Configure Project
      run: mkdir cmake-build-release && cd cmake-build-release && cmake .. -DCMAKE_BUILD_TYPE=Release -G "Ninja"
    - name: Build Unlogic
      run: cd cmake-build-release && cmake --build . --target unlogic
    - name: Build Unlogic Calculator
      run: cd cmake-build-release && cmake --build . --target unlogic-calculator
    - name: Build Tests
      run: cd cmake-build-release && cmake --build . --target unlogic-test
    - name: Run Tests
      run: cd cmake-build-release && ./unlogic-test
